import path from 'path';
import { runCommand, renderRegexFromFile } from '../../../helpers/index.js';
import {
	engageEnv,
	testDataDir,
	e400,
	e500,
	setupEngageAuth,
	initHomeDir,
	resetHomeDir,
} from '../../../helpers/engage-test-helper.js';

describe('axway engage apply', () => {
	describe('help', () => {
		it('should output the help screen', async () => {
			const { status, stdout } = await runCommand([ 'engage', 'apply', '--help' ]);
			expect(stdout).to.match(renderRegexFromFile('templates/help'));
			expect(status).to.equal(0);
		});
	});

	describe('auth required', () => {
		afterEach(resetHomeDir);

		it('should error if not authenticated', async () => {
			initHomeDir('home-local');
			// home-local has valid config but no login tokens
			const { status, stderr } = await runCommand([ 'engage', 'apply', '--file', path.join(testDataDir, 'testInstances1short.yaml') ], { env: engageEnv });
			expect(status).to.equal(1);
			expect(stderr).to.match(renderRegexFromFile('templates/not-authenticated'));
		});
	});

	describe('authenticated', () => {
		/** @type {any} */
		let engageServer;

		beforeEach(async function () {
			engageServer = await setupEngageAuth.call(this);
		});

		afterEach(resetHomeDir);

		it('should error if --file flag is not provided', async () => {
			const { status, stderr } = await runCommand([ 'engage', 'apply' ], { env: engageEnv });
			expect(status).to.equal(1);
			expect(stderr).to.match(renderRegexFromFile('templates/file-required'));
		});

		it('should create and update resources from yaml', async () => {
			// Pre-seed env as existing (to trigger update path) — others will be created
			const envResponse = {
				group: 'management',
				apiVersion: 'v1alpha1',
				kind: 'Environment',
				name: 'testenv1',
				title: 'testenv1 title',
				metadata: { id: 'abc123', resourceVersion: '1', references: [] },
				spec: { description: 'testenv1 description' },
			};
			engageServer.engageResources.set('management/v1alpha1/environments/testenv1', envResponse);

			const { status, stderr } = await runCommand(
				[ 'engage', 'apply', '--file', path.join(testDataDir, 'testInstances1short.yaml') ],
				{ env: engageEnv }
			);

			// Env was updated (pre-existed), others were created
			expect(stderr).to.match(renderRegexFromFile('templates/create-update-success'));
			expect(status).to.equal(0);
		});

		it('should create and update resources from yaml with v1 apiVersion', async () => {
			// Pre-seed env and webhook to trigger update path; APIService and Secret will be created
			const envResponse = { group: 'management', apiVersion: 'v1', kind: 'Environment', name: 'testenv1', metadata: { id: 'abc123', resourceVersion: '1', references: [] }, spec: {} };
			const webhookResponse = { group: 'management', apiVersion: 'v1', kind: 'Webhook', name: 'webhook1', metadata: { scope: { kind: 'Environment', name: 'testenv1' }, resourceVersion: '1', references: [] }, spec: {} };
			engageServer.engageResources.set('management/v1/environments/testenv1', envResponse);
			engageServer.engageResources.set('management/v1/environments/testenv1/webhooks/webhook1', webhookResponse);

			const { status, stderr } = await runCommand(
				[ 'engage', 'apply', '--file', path.join(testDataDir, 'testInstancesV1short.yaml') ],
				{ env: engageEnv }
			);

			expect(status).to.equal(0);
			expect(stderr).to.match(renderRegexFromFile('templates/create-update-success-v1'));
		});

		it('should create resources with --output yaml flag', async () => {
			const { status, stdout } = await runCommand(
				[ 'engage', 'apply', '--file', path.join(testDataDir, 'testInstances1short.yaml'), '--output', 'yaml' ],
				{ env: engageEnv }
			);

			expect(status).to.equal(0);
			expect(stdout).to.match(/kind:\s*Environment/);
		});

		it('should create resources with --output json flag', async () => {
			const { status, stdout } = await runCommand(
				[ 'engage', 'apply', '--file', path.join(testDataDir, 'testInstances1short.json'), '--output', 'json', '--no-banner' ],
				{ env: engageEnv }
			);

			expect(status).to.equal(0);
			const parsed = JSON.parse(stdout);
			expect(parsed).to.be.an('array').with.length.greaterThan(0);
		});

		it('should skip prompt and create resources with missing names when --yes flag is provided', async () => {
			const { status, stderr } = await runCommand(
				[
					'engage', 'apply',
					'--file', path.join(testDataDir, 'testInstancesWithMissingLogicalNames.yaml'),
					'--yes',
				],
				{ env: engageEnv }
			);

			expect(status).to.equal(0);
			expect(stderr).to.match(renderRegexFromFile('templates/autogenerated-name'));
		});

		it('should proceed when prompt is bypassed via AXWAY_TEST_ASK_LIST_RESPONSE=Yes', async () => {
			// Without --yes, askList() is called. The env var makes it return 'Yes'
			// so the batch continues. Note: success messages are silently dropped
			// when spinner=null (set by stopSpin inside onMissingNames), so we
			// verify exit code rather than output content.
			const { status } = await runCommand(
				[ 'engage', 'apply', '--file', path.join(testDataDir, 'testInstancesWithMissingLogicalNames.yaml') ],
				{ env: { ...engageEnv, AXWAY_TEST_ASK_LIST_RESPONSE: 'Yes' } }
			);
			expect(status).to.equal(0);
		});

		it('should abort when prompt is answered No via AXWAY_TEST_ASK_LIST_RESPONSE=No', async () => {
			const { status } = await runCommand(
				[ 'engage', 'apply', '--file', path.join(testDataDir, 'testInstancesWithMissingLogicalNames.yaml') ],
				{ env: { ...engageEnv, AXWAY_TEST_ASK_LIST_RESPONSE: 'No' } }
			);
			expect(status).to.equal(0);
		});

		it('should create and update assets with sub-resources with --output yaml', async () => {
			// Pre-seed asset1 to trigger update; asset2 will be created
			engageServer.engageResources.set('catalog/v1alpha1/assets/testasset1', {
				group: 'catalog', apiVersion: 'v1alpha1', kind: 'Asset', name: 'testasset1',
				metadata: { id: 'id1', resourceVersion: '1', references: [] }, spec: { type: 'API' },
			});

			const { status, stdout } = await runCommand(
				[ 'engage', 'apply', '--file', path.join(testDataDir, 'byKind/Asset/input.yaml'), '--output', 'yaml' ],
				{ env: engageEnv }
			);

			expect(status).to.equal(0);
			expect(stdout).to.match(/kind:\s*Asset/);
			expect(stdout).to.include('testasset1');
			expect(stdout).to.include('testasset2');
		});

		it('should create assets without names using --yes and get autogenerated names', async () => {
			const { status, stderr } = await runCommand(
				[ 'engage', 'apply', '--file', path.join(testDataDir, 'byKind/Asset/input-without-names.yaml'), '--yes' ],
				{ env: engageEnv }
			);

			expect(status).to.equal(0);
			expect(stderr).to.match(renderRegexFromFile('templates/autogenerated-name'));
		});

		it('should update only the specified --subresource', async () => {
			// Pre-seed both assets so GET returns 200 (update path)
			engageServer.engageResources.set('catalog/v1alpha1/assets/testasset1', {
				group: 'catalog', apiVersion: 'v1alpha1', kind: 'Asset', name: 'testasset1',
				metadata: { id: 'id1', resourceVersion: '1', references: [] }, spec: { type: 'API' },
				icon: 'data:image/svg+xml;base64,111', state: 'state 111', 'x-custom': 111,
			});
			engageServer.engageResources.set('catalog/v1alpha1/assets/testasset2', {
				group: 'catalog', apiVersion: 'v1alpha1', kind: 'Asset', name: 'testasset2',
				metadata: { id: 'id2', resourceVersion: '1', references: [] }, spec: { type: 'API' },
				icon: 'data:image/svg+xml;base64,222', state: 'state 222', 'x-custom': 222,
			});

			const { status, stderr } = await runCommand(
				[ 'engage', 'apply', '--file', path.join(testDataDir, 'byKind/Asset/input.yaml'), '--subresource', 'icon' ],
				{ env: engageEnv }
			);

			expect(status).to.equal(0);
			expect(stderr).to.match(renderRegexFromFile('templates/subresource-updated'));
		});

		it('should update product with French language sub-resource', async () => {
			// Pre-seed product so GET returns 200 (update path)
			engageServer.engageResources.set('catalog/v1alpha1/products/test-product-1', {
				group: 'catalog', apiVersion: 'v1alpha1', kind: 'Product', name: 'test-product-1',
				metadata: { id: 'prod1', resourceVersion: '15', references: [] }, spec: { assets: [] },
			});

			const { status, stdout } = await runCommand(
				[
					'engage', 'apply',
					'--file', path.join(testDataDir, 'apiResponses/frenchLanguageDefinition.json'),
					'--output', 'json',
					'--language', 'fr-fr',
					'--no-banner',
				],
				{ env: engageEnv }
			);

			expect(status).to.equal(0);
			const parsed = JSON.parse(stdout);
			expect(parsed).to.be.an('array').with.length.greaterThan(0);
			expect(JSON.stringify(parsed)).to.include('test-product-1');
		});

		it('should create product with French language sub-resource', async () => {
			// No pre-seeded product → POST (create path)
			const { status, stdout } = await runCommand(
				[
					'engage', 'apply',
					'--file', path.join(testDataDir, 'apiResponses/frenchLanguageDefinition.json'),
					'--output', 'json',
					'--language', 'fr-fr',
					'--no-banner',
				],
				{ env: engageEnv }
			);

			expect(status).to.equal(0);
			const parsed = JSON.parse(stdout);
			expect(parsed).to.be.an('array').with.length.greaterThan(0);
			expect(JSON.stringify(parsed)).to.include('test-product-1');
		});

		it('should exit with code 1 when one resource fails with 400 but others succeed', async () => {
			// All GETs return 404 (create path); force APIService POST to return 400
			engageServer.forceErrors.set('POST:management/v1alpha1/environments/testenv1/apiservices', { status: 400, body: e400 });

			const { status, stderr } = await runCommand(
				[ 'engage', 'apply', '--file', path.join(testDataDir, 'testInstances1short.yaml') ],
				{ env: engageEnv }
			);

			expect(status).to.equal(1);
			expect(stderr).to.match(renderRegexFromFile('templates/partial-400-error'));
		});

		it('should exit with code 1 on 500 error from server mid-batch', async () => {
			// Force secrets GET to return 500
			engageServer.forceErrors.set('GET:management/v1alpha1/environments/testenv1/secrets/secret1', { status: 500, body: e500 });

			const { status, stderr } = await runCommand(
				[ 'engage', 'apply', '--file', path.join(testDataDir, 'testInstances1short.yaml') ],
				{ env: engageEnv }
			);

			expect(status).to.equal(1);
			expect(stderr).to.match(renderRegexFromFile('templates/server-error'));
		});

		it('should exit with code 1 when a sub-resource update returns 400', async () => {
			// Pre-seed asset1 (update path); force asset2 state sub-resource PUT to fail
			engageServer.engageResources.set('catalog/v1alpha1/assets/testasset1', {
				group: 'catalog', apiVersion: 'v1alpha1', kind: 'Asset', name: 'testasset1',
				metadata: { id: 'id1', resourceVersion: '1', references: [] }, spec: { type: 'API' },
			});
			engageServer.forceErrors.set('PUT:catalog/v1alpha1/assets/testasset2/state', { status: 400, body: e400 });

			const { status, stdout } = await runCommand(
				[ 'engage', 'apply', '--file', path.join(testDataDir, 'byKind/Asset/input.yaml'), '--output', 'yaml' ],
				{ env: engageEnv }
			);

			expect(status).to.equal(1);
			// With --output yaml, messages go to stdout (renderer uses this.console not spinner)
			expect(stdout).to.match(renderRegexFromFile('templates/validation-error'));
		});

		it('should exit with code 1 on a 400 server error for one resource', async () => {
			const { status } = await runCommand(
				[ 'engage', 'apply', '--file', path.join(testDataDir, 'testInstances1short.json'), '--output', 'json' ],
				{
					env: {
						...engageEnv,
						// Use a non-existing server to trigger error quickly
						AXWAY_CENTRAL_BASE_URL: 'http://127.0.0.1:19999',
					},
				}
			);

			expect(status).to.equal(1);
		});
	});
});

