import Command from '../../lib/command.js';
import { Flags } from '@oclif/core';
import { commonFlags } from '../../lib/engage/flags.js';
import logger, { highlight } from '../../lib/logger.js';
import { OutputTypes, LanguageTypes, ApiServerClientApplyResult, GenericResource, YesNo, YesNoChoices } from '../../lib/types.js';
import { loadAndVerifySpecs, verifyFile } from '../../lib/utils/utils.js';
import Renderer from '../../lib/results/renderer.js';
import { ApiServerClient } from '../../lib/clients-external/apiserverclient.js';
import { DefinitionsManager } from '../../lib/results/DefinitionsManager.js';
import { askList } from '../../lib/utils/basic-prompts.js';
import chalk from 'chalk';

export default class EngageApply extends Command {
	static override summary = 'Update resources from a file.';

	static override aliases = [ 'central:apply' ];

	static override description = `You must be authenticated to update one or more resources.
    Run ${highlight('"axway auth login"')} to authenticate.`;

	static override examples = [
		{
			description: 'Update a resource from a file',
			command: '<%= config.bin %> <%= command.id %> <Resource> --file <FilePath>',
		},
	];

	static override flags = {
		...commonFlags,
		output: Flags.string({
			char: 'o',
			description: `Additional output formats. One of: ${OutputTypes.yaml} | ${OutputTypes.json}`,
		}),
		file: Flags.string({
			char: 'f',
			description: 'Filename to use to create or update the resources. One of: yaml | json',
		}),
		yes: Flags.boolean({
			char: 'y',
			description: 'Automatically reply "yes" to any command prompts.',
		}),
		language: Flags.string({
			description: `Language Codes. One of: Comma Separated values of ${LanguageTypes.French} | ${LanguageTypes.US} | ${LanguageTypes.German} | ${LanguageTypes.Portugese}`,
		}),
		subresource: Flags.string({
			description: 'Name of the 1 subresource to update. Will prevent main resource and all other subresources from being updated.',
		}),
	};

	async run(): Promise<any> {
		const log = logger('EngageApply');

		const { flags, account } = await this.parse(EngageApply);

		let isCmdError = false;

		// need to verify args here since if "-f" is required
		log('verifying args');
		if (!flags.file) {
			throw new Error('File name is required, please provide -f, --file [path] option');
		}

		log(`verifying file: ${flags.file}`);
		verifyFile(flags.file);

		let results: ApiServerClientApplyResult[] = [];
		const render = new Renderer(console, flags.output).startSpin('Creating or updating resource(s)');
		const client = new ApiServerClient({ account, region: flags.region, useCache: flags.cache });
		const defsManager = new DefinitionsManager(client);

		log('executing api calls');
		try {
			await defsManager.init();
			log('loading and verifying specs');
			const { docs, isMissingName } = await loadAndVerifySpecs(flags.file, defsManager.getAllKindsList());
			if (!flags.yes && isMissingName) {
				render.stopSpin();
				if (
					(await askList({
						msg: `As your file contains resources with missing logical names, their logical names will be autogenerated. \nRun ${chalk.cyan(
							'axway engage apply -f <filepath> -o [yaml|json] -y > <output filepath>'
						)} to capture the resource(s) with the autogenerated logical name(s) so you can use them again. \nNOTE: To suppress this prompt in the future, please use the '-y' flag. \nWould you like to continue *without* capturing the resource names in a new file?`,
						choices: YesNoChoices,
						default: YesNo.Yes,
					})) === YesNo.No
				) { process.exit(1); }
				render.startSpin('Creating or updating resource(s)');
			}
			const sortedKindsMap = defsManager.getSortedKindsMap();
			results = await client.bulkCreateOrUpdate(docs as GenericResource[], sortedKindsMap, flags.language, flags.subresource);
			render.bulkCreateOrUpdateResult(results);
			isCmdError = results.some((nextResult) => (nextResult.error?.length ?? 0) > 0);
		} catch (e: any) {
			log('command error', e);
			isCmdError = true;
			if (results.some((nextResult) => nextResult.data)) {
			// Render the results that have completed.
				render.bulkCreateOrUpdateResult(results);
			}
			render.anyError(e);
		} finally {
			log(`command finished, exit with error = ${isCmdError}`);
			render.stopSpin();
			if (isCmdError) {
				process.exit(1);
			}
		}
	}
}
