import Command from '../../lib/command.js';
import { Flags } from '@oclif/core';
import { commonFlags } from '../../lib/engage/flags.js';
import logger, { highlight } from '../../lib/logger.js';
import { OutputTypes, LanguageTypes, YesNo, YesNoChoices } from '../../lib/engage/types.js';
import Renderer from '../../lib/engage/results/renderer.js';
import { applyResources } from '../../lib/engage/services/apply-service.js';
import { askList } from '../../lib/engage/utils/basic-prompts.js';
import chalk from 'chalk';

export default class EngageApply extends Command {
	static override summary = 'Update resources from a file.';

	static override aliases = [ 'central:apply' ];

	static override description = `You must be authenticated to update one or more resources.
    Run ${highlight('"axway auth login"')} to authenticate.`;

	static override examples = [
		{
			description: 'Update a resource from a file',
			command: '<%= config.bin %> <%= command.id %> <Resource> --file <FilePath>',
		},
	];

	static override flags = {
		...commonFlags,
		output: Flags.string({
			char: 'o',
			description: `Additional output formats. One of: ${OutputTypes.yaml} | ${OutputTypes.json}`,
		}),
		file: Flags.string({
			char: 'f',
			description: 'Filename to use to create or update the resources. One of: yaml | json',
		}),
		yes: Flags.boolean({
			char: 'y',
			description: 'Automatically reply "yes" to any command prompts.',
		}),
		language: Flags.string({
			description: `Language Codes. One of: Comma Separated values of ${LanguageTypes.French} | ${LanguageTypes.US} | ${LanguageTypes.German} | ${LanguageTypes.Portugese}`,
		}),
		subresource: Flags.string({
			description: 'Name of the 1 subresource to update. Will prevent main resource and all other subresources from being updated.',
		}),
	};

	async run(): Promise<any> {
		const log = logger('EngageApply');
		const { flags, account } = await this.parse(EngageApply);

		if (!flags.file) {
			throw new Error('File name is required, please provide -f, --file [path] option');
		}

		const render = new Renderer(console, flags.output).startSpin('Creating or updating resource(s)');
		let isCmdError = false;
		try {
			const result = await applyResources({
				account,
				region: flags.region,
				useCache: flags.cache,
				filePath: flags.file,
				language: flags.language,
				subresource: flags.subresource,
				onMissingNames: flags.yes ? undefined : async () => {
					render.stopSpin();
					const answer = await askList({
						msg: `As your file contains resources with missing logical names, their logical names will be autogenerated. \nRun ${chalk.cyan(
							'axway engage apply -f <filepath> -o [yaml|json] -y > <output filepath>'
						)} to capture the resource(s) with the autogenerated logical name(s) so you can use them again. \nNOTE: To suppress this prompt in the future, please use the '-y' flag. \nWould you like to continue *without* capturing the resource names in a new file?`,
						choices: YesNoChoices,
						default: YesNo.Yes,
					});
					render.startSpin('Creating or updating resource(s)');
					return answer !== YesNo.No;
				},
			});

			render.bulkCreateOrUpdateResult(result.results);
			isCmdError = result.hasErrors;
		} catch (e: any) {
			log('command error', e);
			isCmdError = true;
			render.anyError(e);
		} finally {
			log(`command finished, exit with error = ${isCmdError}`);
			render.stopSpin();
			if (isCmdError) {
				process.exit(1);
			}
		}
	}
}
