import Command from '../../../lib/command.js';
import { Flags } from '@oclif/core';
import logger, { highlight } from '../../../lib/logger.js';
import { commonFlags } from '../../../lib/engage/flags.js';
import { CreateCommandResult, OutputTypes, YesNo, YesNoChoices } from '../../../lib/engage/types.js';
import Renderer from '../../../lib/engage/results/renderer.js';
import { askList } from '../../../lib/engage/utils/basic-prompts.js';
import { createResources } from '../../../lib/engage/services/create-service.js';
import chalk from 'chalk';

export default class EngageCreate extends Command {
	static override summary = 'Create one or more resources from a file or stdin.';

	static override aliases = [ 'central:create' ];

	static override description = `You must be authenticated to create one or more resources.
        Run ${highlight('"axway auth login"')} to authenticate.`;

	static override examples = [
		{
			description: 'Create a resource from a file',
			command: '<%= config.bin %> <%= command.id %> <Resource> --file <FilePath>',
		},
	];

	static override flags = {
		...commonFlags,
		output: Flags.string({
			char: 'o',
			description: `Additional output formats. One of: ${OutputTypes.yaml} | ${OutputTypes.json}`,
		}),
		file: Flags.string({
			char: 'f',
			description: 'Filename to use to create or update the resources. One of: yaml | json',
		}),
		yes: Flags.boolean({
			char: 'y',
			description: 'Automatically reply "yes" to any command prompts.',
		}),
	};

	async run(): Promise<any> {
		const log = logger('engage:create');
		let render = new Renderer(console, undefined);
		let commandIsSuccessful = false;
		let result: CreateCommandResult = { results: { success: [], error: [] }, hasErrors: false };
		try {
			const { flags, account } = await this.parse(EngageCreate);
			render = new Renderer(console, flags.output).startSpin('Creating resource(s)');

			if (!flags.file) {
				throw new Error('File name is required, please provide -f, --file [path] option');
			}
			result = await createResources({
				account,
				region: flags.region,
				useCache: !flags.noCache,
				filePath: flags.file,
				onMissingNames: flags.yes ? undefined : async () => {
					render.stopSpin();
					const answer = await askList({
						msg: `As your file contains resources with missing logical names, their logical names will be autogenerated. \nRun ${chalk.cyan(
							'axway engage apply -f <filepath> -o [yaml|json] -y > <output filepath>'
						)} to capture the resource(s) with the autogenerated logical name(s) so you can use them again. \nNOTE: To suppress this prompt in the future, please use the '-y' flag. \nWould you like to continue *without* capturing the resource names in a new file?`,
						choices: YesNoChoices,
						default: YesNo.Yes,
					});
					render.startSpin('Creating resource(s)');
					return answer !== YesNo.No;
				},
			});
			render.bulkResult(result.results, 'has successfully been created.');
			commandIsSuccessful = !result.hasErrors;
		} catch (e: any) {
			log('command error', e);
			// if some calls have been completed, rendering the result
			if (result.results.success.length || result.results.error.length) {
				render.bulkResult(result.results, 'has successfully been created.');
			}
			render.anyError(e);
		} finally {
			log(`command finished, success = ${commandIsSuccessful}`);
			render.stopSpin();
			if (!commandIsSuccessful) {
				process.exit(1);
			}
		}
	}
}
