import path from 'path';
import { runAxwaySync, renderRegexFromFile } from '../../../helpers/index.js';
import {
	engageEnv,
	testDataDir,
	setupEngageAuth,
	initHomeDir,
	resetHomeDir,
} from '../../../helpers/engage-test-helper.js';

describe('axway engage create', () => {
	describe('help', () => {
		it('should output the help screen', async () => {
			const { status, stdout } = await runAxwaySync([ 'engage', 'create', '--help' ]);
			expect(stdout).to.match(renderRegexFromFile('templates/help'));
			expect(status).to.equal(0);
		});
	});

	describe('auth required', () => {
		afterEach(resetHomeDir);

		it('should error if not authenticated', async () => {
			initHomeDir('home-local');
			const { status, stderr } = await runAxwaySync(
				[ 'engage', 'create', '--file', path.join(testDataDir, 'testInstances1short.yaml') ],
				{ env: engageEnv }
			);
			expect(status).to.equal(1);
			expect(stderr).to.match(renderRegexFromFile('templates/not-authenticated'));
		});
	});

	describe('authenticated', () => {
		/** @type {any} */
		let engageServer;

		beforeEach(async function () {
			engageServer = await setupEngageAuth.call(this);
		});

		afterEach(resetHomeDir);

		// --- bulk create from file ---

		describe('bulk create from file', () => {
			it('should error if --file flag is not provided', async () => {
				const { status, stderr } = await runAxwaySync([ 'engage', 'create' ], { env: engageEnv });
				expect(status).to.equal(1);
				expect(stderr).to.match(renderRegexFromFile('templates/file-required'));
			});

			it('should create resources from yaml', async () => {
				const { status, stderr } = await runAxwaySync(
					[ 'engage', 'create', '--file', path.join(testDataDir, 'testInstances1short.yaml') ],
					{ env: engageEnv }
				);
				expect(stderr).to.match(renderRegexFromFile('templates/bulk-create-success'));
				expect(status).to.equal(0);
			});

			it('should create resources with --output yaml', async () => {
				const { status, stdout } = await runAxwaySync(
					[ 'engage', 'create', '--file', path.join(testDataDir, 'testInstances1short.yaml'), '--output', 'yaml' ],
					{ env: engageEnv }
				);
				expect(status).to.equal(0);
				expect(stdout).to.match(/kind:\s*Environment/);
				expect(stdout).to.include('testenv1');
			});

			it('should create resources with --output json', async () => {
				const { status, stdout } = await runAxwaySync(
					[ 'engage', 'create', '--file', path.join(testDataDir, 'testInstances1short.json'), '--output', 'json', '--no-banner' ],
					{ env: engageEnv }
				);
				expect(status).to.equal(0);
				const parsed = JSON.parse(stdout);
				expect(parsed).to.be.an('array').with.length.greaterThan(0);
			});

			it('should create resources with missing logical names with --yes flag', async () => {
				const { status, stderr } = await runAxwaySync(
					[ 'engage', 'create', '--file', path.join(testDataDir, 'envsWithoutLogicalNames.yaml'), '--yes' ],
					{ env: engageEnv }
				);
				expect(status).to.equal(0);
				expect(stderr).to.match(renderRegexFromFile('templates/autogenerated-name'));
			});

			it('should prompt for missing logical names and proceed when answered Yes', async () => {
				const { status } = await runAxwaySync(
					[ 'engage', 'create', '--file', path.join(testDataDir, 'envsWithoutLogicalNames.yaml') ],
					{ env: { ...engageEnv, AXWAY_TEST_ASK_LIST_RESPONSE: 'Yes' } }
				);
				expect(status).to.equal(0);
			});

			it('should abort when missing-name prompt is answered No', async () => {
				const { status } = await runAxwaySync(
					[ 'engage', 'create', '--file', path.join(testDataDir, 'envsWithoutLogicalNames.yaml') ],
					{ env: { ...engageEnv, AXWAY_TEST_ASK_LIST_RESPONSE: 'No' } }
				);
				expect(status).to.equal(0);
			});

			it('should report 400 validation error on resource creation', async () => {
				engageServer.forceErrors.set(
					'POST:management/v1alpha1/environments',
					{ status: 400, body: { errors: [ { status: 400, title: 'Validation error', detail: 'Name is not valid.' } ] } }
				);
				const { status, stderr } = await runAxwaySync(
					[ 'engage', 'create', '--file', path.join(testDataDir, 'testInstances1short.yaml') ],
					{ env: engageEnv }
				);
				expect(status).to.equal(1);
				expect(stderr).to.match(renderRegexFromFile('templates/validation-error'));
			});

			it('should report 500 server error on resource creation', async () => {
				engageServer.forceErrors.set(
					'POST:management/v1alpha1/environments',
					{ status: 500, body: { errors: [ { status: 500, title: 'ApiServer error', detail: 'Internal error.' } ] } }
				);
				const { status } = await runAxwaySync(
					[ 'engage', 'create', '--file', path.join(testDataDir, 'testInstances1short.yaml') ],
					{ env: engageEnv }
				);
				expect(status).to.equal(1);
			});
		});

		// --- create environment by name ---

		describe('create environment by name', () => {
			it('should create a single environment', async () => {
				const { status } = await runAxwaySync(
					[ 'engage', 'create', 'environment', 'testenv1' ],
					{ env: engageEnv }
				);
				expect(status).to.equal(0);
				expect(engageServer.engageResources.has('management/v1alpha1/environments/testenv1')).to.be.true;
			});

			it('should report 400 error when creating environment by name', async () => {
				engageServer.forceErrors.set(
					'POST:management/v1alpha1/environments',
					{ status: 400, body: { errors: [ { status: 400, title: 'Validation error', detail: 'Name is not valid.' } ] } }
				);
				const { status, stderr } = await runAxwaySync(
					[ 'engage', 'create', 'environment', 'bad-name' ],
					{ env: engageEnv }
				);
				expect(status).to.equal(1);
				expect(stderr).to.include('Validation error');
			});
		});
	});
});
